### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by afarahmand** [afarahmand/kicks#5]
- [x] Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by afarahmand** [comment]
I think this feature is ready for review.

**Comment by AAlfarho** [comment]
Great job on the search, defaulting to 9 projects if no search was provided is an interesting way of approaching the search. A couple of minor details.

## Functionality
- [ ] Autofocus the `search input`, that way we can start typing as soon as the page loads. `document.getElementById('<QUERY-SELECTOR>').focus();`
- [ ] After loading `/#/search` we render immediately `Oops! We couldn't find any results.
`, however, we haven't searched anything yet, let's remove this from initial load.

Assign this issue back to me once the latest updates addressing the above issues are pushed to the live version of the app.

**Comment by afarahmand** [comment]
The remaining issues have been resolved: the input text box is autofocused on initial load and the msg is no longer displayed in initial page load.

**Comment by AAlfarho** [comment]
Great job, this MVP is now complete, kudos!
