### ISSUE TITLE
PA Review: Categories / Discover feature

### ISSUE THREAD

**Issue by afarahmand** [afarahmand/kicks#6]
- [x] Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by afarahmand** [comment]
I think this feature is done.  I am awaiting your approval. :)

**Comment by AAlfarho** [comment]
## Functionality
- [ ] As part of the seeding
  - [ ] We should have at least 2-3 projects in each category.
  - [ ] Let's find better images of our projects.
- [ ] By default we are setting the explore to `All` and `Random`, as part of the loadout we should display some projects, I would suggest retrieving some random projects, or in this case 9 projects, same as your idea for the search.
- [ ] The displayed projects could use more information, like how much has been pledged, % funded and days to go, that way users could filter faster which projects to fund.

## Style
- [ ] The style of our `Projects` could use an overhaul, simplifying Kickstarter own display could be a way to go. Minimal but functional and appealing.
![screen shot 2018-02-08 at 2 59 45 pm](https://user-images.githubusercontent.com/1103663/36002937-d0d497a0-0ce0-11e8-9cb1-11e15cde062d.png)


Assign this issue back to me once the latest updates addressing the above issues are pushed to the live version of the app.

**Comment by afarahmand** [comment]
I am currently writing out my seed file but am otherwise done with this task.  I have found all the images I need but still need to type the other project fields.  I will post to Heroku once complete.

**Comment by afarahmand** [comment]
The db is seeded! : ) I think it looks good.

**Comment by AAlfarho** [comment]
New seeding and overall look and feel is great! 
Kudos on the styling and the functionality updates.

This MVP is now complete!
