### ISSUE TITLE
PA Review: A production README

### ISSUE THREAD

**Issue by afarahmand** [afarahmand/kicks#7]
I think we are done with this task.

**Comment by AAlfarho** [comment]
GitHub still has the old default README.

**Comment by afarahmand** [comment]
Ooops, I will fix it ASAP but meanwhile, here is the link to where I made it.[README](https://github.com/afarahmand/kicks/wiki/README.md)

**Comment by AAlfarho** [comment]
README shape is looking good.

- [ ] Remember to add the complete set of technologies you used, like JS ES6, postgres, bcrypt for password salting/hashing, which bundling technologies you used? (Webpack/Gulp/etc).
- [ ] Is there any piece of code you are particularly proud of? Was there a problem you solve in a creative way? Showcase that piece of code.
